/**
 * AVC System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AccountReadAfterAuthenDto {
  id?: number;
  email?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  roleId?: number;
  roleName?: string | null;
  avatar?: string | null;
}
