image: node:latest
stages:
  - build
  - deploy

variables:
  API_URL: 'HIDDEN'
  PRODUCTION: 1
build_admin:
  stage: build
  script:
    - npm ci
    - npm run build:prod -- --project=admin
    - ls .
  only:
    - develop
    - master
  artifacts:
    paths:
      - dist/apps/admin
    expire_in: 24 hrs

pages:
  stage: deploy
  script:
    - echo "----------------------------------------------------------------"
    - echo "Deploy admin site to Gitlab Pages"
    - cp -r dist/apps/admin public
  only:
    - develop
    - master
  artifacts:
    paths:
      - public
    expire_in: 1 hrs
