image: node:latest
stages:
  - build
# - deploy
# - test

variables:
  API_URL: 'https://avc-api.azurewebsites.net'
  PRODUCTION: 1


#########################
###### Build Stage ######
#########################
build_admin:
  stage: build
  script:
    - npm install
    - npm run build:prod -- --project=admin
    - ls .
    - cp -r dist/apps/admin public
  only:
    - develop
    - master
  artifacts:
    paths:
      - public
    expire_in: 24 hrs
